[package]

name = "oyashio"
version = "0.0.3"
authors = ["Chris Gill"]
description = "spmc streams"
repository = "https://github.com/viperscape/oyashio"
readme = "README.md"
license = "MIT"

[dependencies.promise]
git = "https://github.com/viperscape/rust-promise"
rand = "*"