[package]

name = "oyashio"
version = "0.0.4"
authors = ["Chris Gill"]
description = "spmc streams"
repository = "https://github.com/viperscape/oyashio"
readme = "README.md"
license = "MIT"

[dependencies]
promiser = "0.0.5"